LibrarySystem/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("book.urls")),
    path("", include("accounts.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("login/", auth_views.LoginView.as_view(template_name="login.html"), name="login"),
    path("stttings/change_password/", auth_views.PasswordChangeView.as_view(template_name="change_password.html"), name="change_password"),
    path("stttings/change_password/done/", auth_views.PasswordChangeDoneView.as_view(template_name="password_change_done.html"), name="password_change_done"),
    path("profile/", views.profile, name="profile"),
]

book/urls.py
from django.conf import settings    
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("<int:pk>/", views.book_detail, name="book_detail"),
    path("addbook/", views.addbook, name="addbook"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

book/models.py
from django.db import models


class Books(models.Model):
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField()
    rating = models.IntegerField()
    release_date = models.DateField(auto_now=False, auto_now_add=False)
    cover_photo = models.ImageField(upload_to="service/covers/", null=True)
    book_file = models.FileField(upload_to="service/files/", null=True)
    
    def __str__(self):
        return self.name

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=255, required=True, widget=forms.EmailInput())
    
    class Meta:
        model=User
        fields = {"username", "email", "password1", "password2"}
        

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login as auth_login
from .forms import SignUpForm
from django.contrib.auth.decorators import login_required


def signup(request):
    form = SignUpForm()
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect("dashboard")

    return render(request, "signup.html", {"form": form})


@login_required
def profile(request):
    return render(request, "profile.html")

book/views.py
from django.shortcuts import render, HttpResponse
from .models import Books
from django.contrib.auth.decorators import login_required


def dashboard(request):
    books = Books.objects.all()
    return render(request, 'book_index.html', {'books': books})


@login_required
def book_detail(request, pk):
    book = Books.objects.get(pk=pk)
    return render(request, 'book_detail.html', {'book': book})


@login_required
def addbook(request):
    books = Books.objects.all()
    if request.method == "POST":
        
        name = request.POST['name']
        author = request.POST['author']
        description = request.POST['description']
        rating = request.POST['rating']
        release_date = request.POST['release_date']
        cover_photo = request.FILES['cover_photo']
        book_file = request.FILES['book_file']
        book = Books.objects.create(
            name=name,
            author=author,
            description=description,
            rating=rating,
            release_date=release_date,
            cover_photo=cover_photo,
            book_file=book_file,
        )
        book.save()
    return render(request, "addbook.html", {'books': books})

accounts/templates/change_password.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
    <br>
    <br>
    {% if form.non_field_errors%}
        <div class="alert alert-danger" role="alerts">
        {%for error in form.non_field_errors%}
            <p {%if forloop.last%} class="mb-0" {%endif%}>{{error}}</p>
        {%endfor%}
        </div>
    {%endif%}
    <div class="container">
        <section class="tab-pane fade show active">
            <div class="breadcrumb my-4">
                <li class="breadcrumb-item "><a href="{% url 'dashboard' %}">Books</a></li>
                <li class="breadcrumb-item ">Change Password</li>
            </div>
            <br>
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    {{field.label_tag}}
                    <div class="form-outline mb-4">
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback" >
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                <br>
                <button type="submit" class="btn btn-primary btn-block mb-4">
                    Change Password
                </button>
            </form>
        </section>
    </div>
{% endblock %}

accounts/templates/login.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<br>
<br>
{% if form.non_field_errors%}
    <div class="alert alert-danger" role="alerts">
    {%for error in form.non_field_errors%}
        <p {%if forloop.last%} class="mb-0" {%endif%}>{{error}}</p>
    {%endfor%}
    </div>
{%endif%}
<div class="container">
        <section class="tab-pane fade show active">
            <h1>Login</h1>
            <br>
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    {{field.label_tag}}
                    <input type="hidden" name="next" value="{{ next }}">
                    <div class="form-outline mb-4">
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback" >
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                <br>
                <button type="submit" class="btn btn-primary btn-block mb-4">
                    LOG IN
                </button>
                <br>
                <div class="card-footer text-muted text-center">
                    Create New Account? <a href="{% url 'signup' %}">Sign up</a>
                </div>
            </form>
        </section>  
    </div>
{% endblock %}

accounts/templates/password_change_done.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
<br>
<div class="container">
        <section class="tab-pane fade show active">
            <div class="breadcrumb my-4">
                <li class="breadcrumb-item"><a href="{% url 'change_password' %}" >Change Password</a></li>
                <li class="breadcrumb-item active">Success</li>
            </div>
            <br>
            <div class="alert alert-warning" role="alert">
                <li class="breadcrumb-item">Success! Your password has been changed ✅</li>
            </div>
            <br>
            <br>
                <a class="btn btn-info" href="{% url 'dashboard' %}" >Return To Home 🏠</a>
        </section>  
    </div>
{% endblock %}

accounts/templates/profile.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block cssnew %}
    <style>
        .emp-profile{
            padding: 3%;
            margin-top: 3%;
            margin-bottom: 3%;
            border-radius: 0.5rem;
            background: #fff;
        }
        .profile-img{
            text-align: center;
        }
        .profile-img img{
            width: 70%;
            height: 90%;
        }
        .profile-img .file {
            position: relative;
            overflow: hidden;
            margin-top: -20%;
            width: 70%;
            border: none;
            border-radius: 0;
            font-size: 15px;
            background: #212529b8;
        }
        .profile-img .file input {
            position: absolute;
            opacity: 0;
            right: 0;
            top: 0;
        }
        .profile-head h5{
            color: #333;
        }
        .profile-head h6{
            color: #0062cc;
        }
        .profile-edit-btn{
            border: none;
            border-radius: 1.5rem;
            width: 100%;
            padding: 2%;
            font-weight: 600;
            color: #6c757d;
            cursor: pointer;
        }
        .proile-rating{
            font-size: 12px;
            color: #818182;
            margin-top: 5%;
        }
        .proile-rating span{
            color: #495057;
            font-size: 15px;
            font-weight: 600;
        }
        .profile-head .nav-tabs{
            margin-bottom:5%;
        }
        .profile-head .nav-tabs .nav-link{
            font-weight:600;
            border: none;
        }
        .profile-head .nav-tabs .nav-link.active{
            border: none;
            border-bottom:2px solid #0062cc;
        }
        .profile-work{
            padding: 14%;
            margin-top: -15%;
        }
        .profile-work p{
            font-size: 12px;
            color: #818182;
            font-weight: 600;
            margin-top: 10%;
        }
        .profile-work a{
            text-decoration: none;
            color: #495057;
            font-weight: 600;
            font-size: 14px;
        }
        .profile-work ul{
            list-style: none;
        }
        .profile-tab label{
            font-weight: 600;
        }
        .profile-tab p{
            font-weight: 600;
            color: #0062cc;
        }        
    </style>
{% endblock %}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item "><a href="{% url 'dashboard' %}">Books</a></li>
        <li class="breadcrumb-item ">Profile Information</li>
    </ol>
{% endblock %}
{% block content %}
<div class="container emp-profile">
    <form method="post" novalidate>
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="https://www.khabrabyad.com/UserFiles/NewsSizes/600/2020/01/27/4067.jpg?200128140000" alt=""/>
                    {% comment %} <div class="file btn btn-lg btn-primary">
                        Change Photo
                        <input type="file" name="file"/>
                    </div> {% endcomment %}
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                            <h3>
                                {{ user.username }}
                            </h3>
                            <h6>
                                Book Reader
                            </h6>
                            <p class="proile-rating">RANKINGS : <span>8/10</span></p>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                        </li>
                        {% comment %} <li class="nav-item">
                            <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Timeline</a>
                        </li> {% endcomment %}
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <a class="btn btn-outline-primary" href="{% url 'change_password' %}">Change Password</a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        <div class="row">
                            <div class="col-md-6">
                                <label>User Id</label>
                            </div>
                            <div class="col-md-6">
                                <p>000{{ user.id }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Name</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ user.username }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Email</label>
                            </div>
                            <div class="col-md-6">
                                <p>{{ user.email }}</p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <label>Phone</label>
                            </div>
                            <div class="col-md-6">
                                <p>059 591 1694</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>           
</div>
{% endblock %}

accounts/templates/signup.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block content %}
    <br>
    <br>
    {% if form.non_field_errors%}
        <div class="alert alert-danger" role="alerts">
        {%for error in form.non_field_errors%}
            <p {%if forloop.last%} class="mb-0" {%endif%}>{{error}}</p>
        {%endfor%}
        </div>
    {%endif%}
    <div class="container">
        <section class="tab-pane fade show active">
            <h1 class="card-title">Sign Up</h1>
            <br>
            <form method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    {{field.label_tag}}
                    <div class="form-outline mb-4">
                        {% render_field field class="form-control is-invalid" %}
                        {% for error in field.errors %}
                            <div class="invalid-feedback" >
                                {{ error }}
                            </div>
                        {% endfor %}
                    </div>
                {% endfor %}
                <br>
                <button type="submit" class="btn btn-primary btn-block mb-4">
                    SIGN IN
                </button>
                <br>
                <div class="card-footer text-muted text-center">
                    Already have an account? <a href="{% url 'login' %}">Log in</a>
                </div>
            </form>
        </section>  
    </div>
{% endblock %}

book/templates/addbook.html
{% extends "base.html" %}
{% block breadcrumb %} 
<ol class="breadcrumb my-4">
    <li class="breadcrumb-item "><a href="{% url 'dashboard' %}">Books</a></li>
    <li class="breadcrumb-item ">Add New Book</li>
</ol>
{% endblock %}
{% block content %}
    <section class="tab-pane fade show active">
        <div class="container">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">Name Book</label>
                    <input type="text" class="form-control" id="id_name" name="name">
                </div>
                <div class="form-group">
                    <label for="id_author">Author</label>
                    <input type="text" class="form-control" id="id_author" name="author">
                </div>
                <div class="form-group">
                    <label for="id_description">Description</label>
                    <textarea class="form-control" id="id_description" name="description" rows="4"></textarea>
                </div>
                <div class="form-group">
                    <label for="id_rating">Rating</label>
                    <input type="number" class="form-control" id="id_rating" name="rating">
                </div>
                <div class="form-group">
                    <label for="id_release_date">Release Date</label>
                    <input type="date" class="form-control" id="id_release_date" name="release_date">
                </div>
                <div class="form-group">
                    <label for="id_cover_photo">Cover Photo</label>
                    <input type="file" class="form-control" id="id_cover_photo" name="cover_photo">
                </div>
                <div class="form-group">
                    <label for="id_book_file">Book File</label>
                    <input type="file" class="form-control" id="id_book_file" name="book_file">
                </div>
                <br>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary btn-block mb-4">
                        Add
                    </button>
                </div>
                <br>
            </form>
        </div>
    </section> 
{% endblock %}

book/templates/base.html
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="https://static-00.iconduck.com/assets.00/crow-icon-512x409-aqj1chak.png" type="image/x-icon">
        <title>Palestine Library</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
            integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        {% block cssnew %}{% endblock %}
    </head>
    <body>
        {% block navbar %}{% endblock %}
        <div class="container">
            {% block breadcrumb %}
                
            {% endblock %}
            {% block content %}
            {% endblock %}
        </div>  
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
    </body>
</html> 

book/templates/book_detail.html
{% extends "base.html" %}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item "><a href="{% url 'dashboard' %}">Books</a></li>
        <li class="breadcrumb-item ">{{ book.name }}</li>
    </ol>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-6">
        <img src="{{ book.cover_photo.url }}" alt="">
        
    </div>
    <div class="col-6">
        <h3>About the book:</h3>
        <p>{{ book.description }}</p>
        <h3>Author:</h3>
        <p>{{ book.author }}</p>
        <h3>Published:</h3>
        <p>{{ book.release_date }}</p>
        <h3>Rating:</h3>
        <h4>{{ book.rating }}/5<img src="https://t4.ftcdn.net/jpg/02/74/86/39/360_F_274863915_4JnfDXwTaTsjg5w5e7keElOipBswjAte.jpg" alt="" width="150"></h4>
        <br>
        <a href="{{ book.book_file.url }}" Download class="btn btn-secondary btn-lg btn-block">
            Download 
        </a>
    </div>
</div>
{% endblock %}

book/templates/book_index.html
{% extends "base.html" %}
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}
{% block breadcrumb %}
    <ol class="breadcrumb my-4">
        <li class="breadcrumb-item active">Books</li>
    </ol>
{% endblock %}
{% block content %}
    <div class="row">
        {% for b in books %}
            <div class="col-md-4">
                <div class="card mb-2">
                    <img class="card-img-top" src="{{ b.cover_photo.url }}" width="100" height="400">
                    <div class="card-body">
                        <h5 class="card-title">{{ b.name }}</h5>
                        <p class="card-text">{{ b.author }}</p>
                        <a href="{% url 'book_detail' b.pk %}" class="btn btn-primary btn-lg btn-block">
                            Download
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

book/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'dashboard' %}">Palestine Library</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Welcome {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                            <a class="dropdown-item" href="{% url 'profile' %}">My account</a>
                            <a class="dropdown-item" href="{% url 'change_password' %}">Change password</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                        </div>
                    </li>
                </ul>
            {% else %}
                <form class="form-inline ml-auto">
                    <a href="{%url 'login'%}" class="btn btn-outline-secondary">login</a>
                    <a href="{%url 'signup'%}" class="btn btn-primary ml-2">Signup</a>
                </form>
            {% endif %}
        </div>
    </div>
</nav>